template = {template block, {line break}};

template block = code block
               | tag block
               | text block
               | html block
               | yield block
               | extend block
               | section block
               | include block
               | comment block
               | variable block
               | iteration block
               | conditional block;

code block              = language name, ':', [line of code], [line break, indent, {line of code}];
language name           = 'css' | 'javascript';
line of code            = { any character }, line break;

tag block = tag identifier, {attribute}, [tag content], [line break, indent, {template block}];

tag identifier = [tag name], [tag id],    {tag class}
               | [tag name], {tag class}, [tag id];

name              = letter, {letter | digit | '-', '_'};
tag name          = name;
tag id            = '#', name;
tag class         = '.', name;
tag content       = variable content | text content;
variable content  = '=', ['='], variable;
text content      = !'=', {text incl vars};
text incl vars    = {{any character}, {variable | ('{', expression, '}')}};
attribute         = attribute name, '=', attribute value;
attribute value   = string | boolean | variable;
boolean           = 'false' | 'true';


text block = '|', {text incl vars}, [line break, indent, {text incl vars}];


# the regular expressions are here, because I don't know how to write this in real good enbf:

attribute name  = /[^\s\/>"\'=]+/;
string          = /"[^"\n]"|'[^'\n]'/;
variable        = /[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*/;
any character   = /./;